#!/bin/bash

declare -a address=(21 22 23 24 25 26 30 31 32 33 36 37 38);

function startNodes {
	for((i=0; i<$1; i++))
	do
		ssh -t 10.66.66.${address[i]} "cd narayana/kvstore ; java -cp target/classes:target/dependency/* org.jboss.narayana.infinispankvstore.MillNode" &
		sleep 2
	done
}

function stopNodes {
	for((i=0; i<$1; i++))
	do
		ssh -t 10.66.66.${address[i]} ./narayana/kvstore/stopNodes &
	done
	sleep 5
}

# stopNodes 13

n=1

function test {
	echo "$1 NODE TEST"
	startNodes $1
	./build.sh -f kvstore/pom.xml test -Dtest=org.jboss.narayana.infinispankvstore.Mill* 
	stopNodes $1
	sleep 5

}

test 1
test 3
test 6
test 9
test 12
